version: '3.8'
services:
  my-app-database:
    image: mysql:8.0
    container_name: my-app-database
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./database/init/:/docker-entrypoint-initdb.d/
    ports:
      - "3307:3306"
    networks:
      - my-app-network

  my-app-redis:
    image: redis:6
    container_name: my-app-redis
#    restart: always
    ports:
      - "6379:6379"
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge

volumes:
  mysql_data: